apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-reporting-system
  namespace: ba-cirt-infra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: incident-reporting-system
  template:
    metadata:
      labels:
        app: incident-reporting-system
    spec:
      containers:
        - name: app
          image: bytebender0/incident-reporting-system:6
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >
                -Dspring.datasource.url=jdbc:postgresql://postgres:5432/incident_db
                -Dspring.datasource.username=incident_user
                -Dspring.datasource.password=SecurePass123!
                -Dspring.jpa.hibernate.ddl-auto=update
