apiVersion: v1
kind: Service
metadata:
  name: incident-reporting-system
  namespace: ba-cirt-infra
spec:
  selector:
    app: incident-reporting-system
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
